# @package _global_

defaults:
  - _self_
  - data: eco_data.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: RFVGGish.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
